package com.CricketHub.demo.Model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;

@Entity
public class Admin { 
    // Annotation indicating that the following field is a primary key in the database.
    @Id
    // Annotation indicating that the primary key's value is automatically generated by the database.
    @GeneratedValue
    private Long id;

    // Declare a private field to store the admin's name.
    private String name;

    // Declare a private field to store the admin's password.
    private String password;
    
    // Getter method for retrieving the value of the 'id' field.
    public Long getId() {
        return id;
    }

    // Setter method for setting the value of the 'id' field.
    public void setId(Long id) {
        this.id = id;  //this.id = id; is assigning the value of the id parameter (which represents the new value you want to set) to the id field of the current Admin object.
    }
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return password;
    }
    public void setPassword(String password) {
        this.password = password;
    }   
}
